# Generated by Django 2.0.5 on 2019-08-26 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20190824_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hint',
        ),
    ]
